// Code generated by protoc-gen-gogo.
// source: github.com/TheThingsNetwork/ttn/api/noc/noc.proto
// DO NOT EDIT!

/*
	Package noc is a generated protocol buffer package.

	It is generated from these files:
		github.com/TheThingsNetwork/ttn/api/noc/noc.proto

	It has these top-level messages:
*/
package noc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import gateway "github.com/TheThingsNetwork/ttn/api/gateway"
import router "github.com/TheThingsNetwork/ttn/api/router"
import broker "github.com/TheThingsNetwork/ttn/api/broker"
import handler "github.com/TheThingsNetwork/ttn/api/handler"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Monitor service

type MonitorClient interface {
	GatewayLocation(ctx context.Context, opts ...grpc.CallOption) (Monitor_GatewayLocationClient, error)
	GatewayUplink(ctx context.Context, opts ...grpc.CallOption) (Monitor_GatewayUplinkClient, error)
	RouterStatus(ctx context.Context, opts ...grpc.CallOption) (Monitor_RouterStatusClient, error)
	BrokerStatus(ctx context.Context, opts ...grpc.CallOption) (Monitor_BrokerStatusClient, error)
	HandlerStatus(ctx context.Context, opts ...grpc.CallOption) (Monitor_HandlerStatusClient, error)
}

type monitorClient struct {
	cc *grpc.ClientConn
}

func NewMonitorClient(cc *grpc.ClientConn) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) GatewayLocation(ctx context.Context, opts ...grpc.CallOption) (Monitor_GatewayLocationClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Monitor_serviceDesc.Streams[0], c.cc, "/noc.Monitor/GatewayLocation", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorGatewayLocationClient{stream}
	return x, nil
}

type Monitor_GatewayLocationClient interface {
	Send(*gateway.GPSMetadata) error
	CloseAndRecv() (*google_protobuf.Empty, error)
	grpc.ClientStream
}

type monitorGatewayLocationClient struct {
	grpc.ClientStream
}

func (x *monitorGatewayLocationClient) Send(m *gateway.GPSMetadata) error {
	return x.ClientStream.SendMsg(m)
}

func (x *monitorGatewayLocationClient) CloseAndRecv() (*google_protobuf.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *monitorClient) GatewayUplink(ctx context.Context, opts ...grpc.CallOption) (Monitor_GatewayUplinkClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Monitor_serviceDesc.Streams[1], c.cc, "/noc.Monitor/GatewayUplink", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorGatewayUplinkClient{stream}
	return x, nil
}

type Monitor_GatewayUplinkClient interface {
	Send(*router.UplinkMessage) error
	CloseAndRecv() (*google_protobuf.Empty, error)
	grpc.ClientStream
}

type monitorGatewayUplinkClient struct {
	grpc.ClientStream
}

func (x *monitorGatewayUplinkClient) Send(m *router.UplinkMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *monitorGatewayUplinkClient) CloseAndRecv() (*google_protobuf.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *monitorClient) RouterStatus(ctx context.Context, opts ...grpc.CallOption) (Monitor_RouterStatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Monitor_serviceDesc.Streams[2], c.cc, "/noc.Monitor/RouterStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorRouterStatusClient{stream}
	return x, nil
}

type Monitor_RouterStatusClient interface {
	Send(*router.Status) error
	CloseAndRecv() (*google_protobuf.Empty, error)
	grpc.ClientStream
}

type monitorRouterStatusClient struct {
	grpc.ClientStream
}

func (x *monitorRouterStatusClient) Send(m *router.Status) error {
	return x.ClientStream.SendMsg(m)
}

func (x *monitorRouterStatusClient) CloseAndRecv() (*google_protobuf.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *monitorClient) BrokerStatus(ctx context.Context, opts ...grpc.CallOption) (Monitor_BrokerStatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Monitor_serviceDesc.Streams[3], c.cc, "/noc.Monitor/BrokerStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorBrokerStatusClient{stream}
	return x, nil
}

type Monitor_BrokerStatusClient interface {
	Send(*broker.Status) error
	CloseAndRecv() (*google_protobuf.Empty, error)
	grpc.ClientStream
}

type monitorBrokerStatusClient struct {
	grpc.ClientStream
}

func (x *monitorBrokerStatusClient) Send(m *broker.Status) error {
	return x.ClientStream.SendMsg(m)
}

func (x *monitorBrokerStatusClient) CloseAndRecv() (*google_protobuf.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *monitorClient) HandlerStatus(ctx context.Context, opts ...grpc.CallOption) (Monitor_HandlerStatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Monitor_serviceDesc.Streams[4], c.cc, "/noc.Monitor/HandlerStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorHandlerStatusClient{stream}
	return x, nil
}

type Monitor_HandlerStatusClient interface {
	Send(*handler.Status) error
	CloseAndRecv() (*google_protobuf.Empty, error)
	grpc.ClientStream
}

type monitorHandlerStatusClient struct {
	grpc.ClientStream
}

func (x *monitorHandlerStatusClient) Send(m *handler.Status) error {
	return x.ClientStream.SendMsg(m)
}

func (x *monitorHandlerStatusClient) CloseAndRecv() (*google_protobuf.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Monitor service

type MonitorServer interface {
	GatewayLocation(Monitor_GatewayLocationServer) error
	GatewayUplink(Monitor_GatewayUplinkServer) error
	RouterStatus(Monitor_RouterStatusServer) error
	BrokerStatus(Monitor_BrokerStatusServer) error
	HandlerStatus(Monitor_HandlerStatusServer) error
}

func RegisterMonitorServer(s *grpc.Server, srv MonitorServer) {
	s.RegisterService(&_Monitor_serviceDesc, srv)
}

func _Monitor_GatewayLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitorServer).GatewayLocation(&monitorGatewayLocationServer{stream})
}

type Monitor_GatewayLocationServer interface {
	SendAndClose(*google_protobuf.Empty) error
	Recv() (*gateway.GPSMetadata, error)
	grpc.ServerStream
}

type monitorGatewayLocationServer struct {
	grpc.ServerStream
}

func (x *monitorGatewayLocationServer) SendAndClose(m *google_protobuf.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *monitorGatewayLocationServer) Recv() (*gateway.GPSMetadata, error) {
	m := new(gateway.GPSMetadata)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Monitor_GatewayUplink_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitorServer).GatewayUplink(&monitorGatewayUplinkServer{stream})
}

type Monitor_GatewayUplinkServer interface {
	SendAndClose(*google_protobuf.Empty) error
	Recv() (*router.UplinkMessage, error)
	grpc.ServerStream
}

type monitorGatewayUplinkServer struct {
	grpc.ServerStream
}

func (x *monitorGatewayUplinkServer) SendAndClose(m *google_protobuf.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *monitorGatewayUplinkServer) Recv() (*router.UplinkMessage, error) {
	m := new(router.UplinkMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Monitor_RouterStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitorServer).RouterStatus(&monitorRouterStatusServer{stream})
}

type Monitor_RouterStatusServer interface {
	SendAndClose(*google_protobuf.Empty) error
	Recv() (*router.Status, error)
	grpc.ServerStream
}

type monitorRouterStatusServer struct {
	grpc.ServerStream
}

func (x *monitorRouterStatusServer) SendAndClose(m *google_protobuf.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *monitorRouterStatusServer) Recv() (*router.Status, error) {
	m := new(router.Status)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Monitor_BrokerStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitorServer).BrokerStatus(&monitorBrokerStatusServer{stream})
}

type Monitor_BrokerStatusServer interface {
	SendAndClose(*google_protobuf.Empty) error
	Recv() (*broker.Status, error)
	grpc.ServerStream
}

type monitorBrokerStatusServer struct {
	grpc.ServerStream
}

func (x *monitorBrokerStatusServer) SendAndClose(m *google_protobuf.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *monitorBrokerStatusServer) Recv() (*broker.Status, error) {
	m := new(broker.Status)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Monitor_HandlerStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitorServer).HandlerStatus(&monitorHandlerStatusServer{stream})
}

type Monitor_HandlerStatusServer interface {
	SendAndClose(*google_protobuf.Empty) error
	Recv() (*handler.Status, error)
	grpc.ServerStream
}

type monitorHandlerStatusServer struct {
	grpc.ServerStream
}

func (x *monitorHandlerStatusServer) SendAndClose(m *google_protobuf.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *monitorHandlerStatusServer) Recv() (*handler.Status, error) {
	m := new(handler.Status)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Monitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "noc.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GatewayLocation",
			Handler:       _Monitor_GatewayLocation_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GatewayUplink",
			Handler:       _Monitor_GatewayUplink_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RouterStatus",
			Handler:       _Monitor_RouterStatus_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BrokerStatus",
			Handler:       _Monitor_BrokerStatus_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "HandlerStatus",
			Handler:       _Monitor_HandlerStatus_Handler,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptorNoc,
}

func init() {
	proto.RegisterFile("github.com/TheThingsNetwork/ttn/api/noc/noc.proto", fileDescriptorNoc)
}

var fileDescriptorNoc = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x90, 0xcb, 0x4a, 0xc3, 0x40,
	0x14, 0x86, 0x8d, 0x82, 0xc2, 0x60, 0xad, 0x0c, 0xea, 0xa2, 0x42, 0xd6, 0xae, 0x66, 0x50, 0x17,
	0x5e, 0x56, 0x5a, 0x90, 0xba, 0xb0, 0x22, 0xb6, 0x3e, 0xc0, 0x24, 0x1d, 0x27, 0x43, 0xd2, 0x39,
	0x61, 0x72, 0x42, 0xe9, 0x9b, 0xf8, 0x34, 0xae, 0x5d, 0xfa, 0x08, 0x12, 0x5f, 0x44, 0x9a, 0x99,
	0x71, 0xd9, 0xcb, 0x22, 0xfc, 0x9c, 0x70, 0xbe, 0x9f, 0x39, 0x1f, 0x39, 0x57, 0x1a, 0xb3, 0x3a,
	0x61, 0x29, 0x4c, 0xf9, 0x38, 0x93, 0xe3, 0x4c, 0x1b, 0x55, 0x3d, 0x4b, 0x9c, 0x81, 0xcd, 0x39,
	0xa2, 0xe1, 0xa2, 0xd4, 0xdc, 0x40, 0xba, 0xf8, 0x58, 0x69, 0x01, 0x81, 0xee, 0x18, 0x48, 0x7b,
	0xa7, 0x0a, 0x40, 0x15, 0x92, 0xb7, 0xbf, 0x92, 0xfa, 0x9d, 0xcb, 0x69, 0x89, 0x73, 0xb7, 0xd1,
	0xbb, 0x59, 0xa7, 0x54, 0x09, 0x94, 0x33, 0x31, 0x0f, 0xe9, 0xd1, 0xab, 0x75, 0x50, 0x0b, 0x35,
	0x4a, 0xeb, 0x63, 0x13, 0x30, 0xb1, 0x90, 0x4b, 0xeb, 0x63, 0x93, 0xc7, 0x66, 0xc2, 0x4c, 0x0a,
	0x69, 0x43, 0x3a, 0xf4, 0xe2, 0x73, 0x9b, 0xec, 0x0d, 0xc1, 0x68, 0x04, 0x4b, 0xef, 0x49, 0x77,
	0xe0, 0x2e, 0x79, 0x82, 0x54, 0xa0, 0x06, 0x43, 0x8f, 0x58, 0xb8, 0x6d, 0xf0, 0x32, 0x1a, 0x4a,
	0x14, 0x13, 0x81, 0xa2, 0x77, 0xc2, 0x9c, 0x3a, 0x16, 0xd4, 0xb1, 0x87, 0x85, 0xba, 0xb3, 0x88,
	0xde, 0x91, 0x8e, 0xaf, 0x78, 0x2b, 0x0b, 0x6d, 0x72, 0x7a, 0xcc, 0xfc, 0x89, 0x6e, 0x1e, 0xca,
	0xaa, 0x12, 0x4a, 0x2e, 0x69, 0xb8, 0x26, 0xfb, 0xaf, 0x2d, 0x31, 0x42, 0x81, 0x75, 0x45, 0x0f,
	0x42, 0x81, 0x9b, 0x97, 0x93, 0xfd, 0xd6, 0xca, 0x3f, 0xe9, 0x25, 0xad, 0x24, 0x6f, 0x49, 0xe7,
	0xd1, 0x59, 0xf1, 0x68, 0x97, 0x05, 0x4b, 0xab, 0xd8, 0xfe, 0xe1, 0x57, 0x13, 0x47, 0xdf, 0x4d,
	0x1c, 0xfd, 0x34, 0x71, 0xf4, 0xf1, 0x1b, 0x6f, 0x25, 0xbb, 0xed, 0xce, 0xe5, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf8, 0xba, 0x29, 0x05, 0x98, 0x02, 0x00, 0x00,
}
