id: dev
debug: true
discovery-server: "localhost:1900"
auth-servers:
  ttn-account: "https://account.thethingsnetwork.org"
  ttn-account-staging: "https://staging.account.thethingsnetwork.org"
tls: true
key-dir: "./.env/broker/"

auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0dG4tYWNjb3VudC1zdGFnaW5nIiwic3ViIjoiZGV2IiwidHlwZSI6ImJyb2tlciIsImlhdCI6MTQ3MjgxNzk1MX0.m3sMJDaXcsAxROlCOqbidv5cQf1iau99N5aIC9D4rH9lCzl__Z6sVkMOqDrdDska1lxuKlkr7dQEDvU5ujUmOSKC3riMZFtOnvA_7NQAR8Q1i6JxHVg3OKpml513nbOKynPn8Vb2oEN0S1yyfkLepbMfAuJKzxPUL92vZcKX6GgyV51nnfYZp-HksqkaFK7zm2wbQQ_xqouLZ_mibRdMyryFfv5mDnZ3K1LCHXcv_FanoMA8hvjKq3pKwflI2vJPSNGmwftPL0oG7t4MBXkx3IqthxhyymyYbukcC1UBtwtvo3Now2cbbfwatBPAEqUkvcXe-LK4YW1QsYB0xs8iOQ

broker:
  networkserver-cert: ./.env/broker/networkserver.cert
  networkserver-token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0Njk3OTQzNTksIm5iZiI6MTQ2OTc5NDM1OSwic3ViIjoiZGV2In0.Xj1AFEAblzFLdS5cUiDrG773EqHazARvGdkTHFoPa_c0XGhdKSrevVpTNkzvcXeTQTWnTQrg1t98atNIk7F13Q
