id: dev
debug: true
discovery-server: "localhost:1900"
auth-servers:
  ttn-account: "https://account.thethingsnetwork.org"
  ttn-account-staging: "https://staging.account.thethingsnetwork.org"
tls: true
key-dir: "./.env/router/"

auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0dG4tYWNjb3VudC1zdGFnaW5nIiwic3ViIjoiZGV2IiwidHlwZSI6InJvdXRlciIsImlhdCI6MTQ3MjgxNzk1MX0.Rjv2QHMAdhrZpc7Nf1HdUG1EoZqURr-PKWZaU7Xz7p30FMBxDXUDUtDbcILKbjstlczVOdHGQnAOf-rwzeIrXJ5051KopcDYcmpRwqJQHnKmzFClw5gs-1uAYSnwcEvpsGaFDS8Q7qc6X0m-5lFnFeHAtgVPa80joAw6QBPaTwW3KHvoY_a2htjk8tUQhVlL-wTCnnPMeUGIYJwHFIRXZW3Wk32XLWwF2w8fimVFgfr8yBQMLucbQ-CNEqcuC8tU8H46kPKCugadY6enmaOVVgeGFK1s9OEm4oHhYMJkE0agY7FZBPVEyl9bVxpCRor4H60MebA5U7xQ9tQQlP2ndQ
