id: dev
debug: true
discovery-address: "localhost:1900"
auth-servers:
  ttn-account-v2: "https://account.thethingsnetwork.org"
tls: true
key-dir: "./.env/handler/"
handler:
  amqp-address: localhost:5672
  mqtt-address: localhost:1883

auth-token: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODE4ODMwNjksImlzcyI6ImxvY2FsIiwibmJmIjoxNDgxODgzMDY5LCJzdWIiOiJkZXYiLCJ0eXBlIjoiaGFuZGxlciJ9.ZXUIb2hpaMK9p_F92KtRuCf77w4fuf4w9wrd0ym4WpEq0y2WPIOPBCLX_a_Iu33pr2GwXwlJcg6Ig9J29hnysg
