id: dev
debug: true
discovery-server: "localhost:1900"
auth-servers:
  ttn-account: "https://account.thethingsnetwork.org"
  ttn-account-staging: "https://staging.account.thethingsnetwork.org"
tls: true
key-dir: "./.env/handler/"

auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0dG4tYWNjb3VudC1zdGFnaW5nIiwic3ViIjoiZGV2IiwidHlwZSI6ImhhbmRsZXIiLCJpYXQiOjE0NzI4MTc5NTJ9.XyaTta7R66bfaCS4rzNYayzejE7nP7CcleksPyk71LsDkyMetFE_dJ-EP1Lp6Lys7yBILO4ax5tfuswBwvXg2sOIBIT30SPuTaJ62HidU6We_DQHBvHMSkdSOMnk3WNJ5rWhogga1rSHiKnJH56CqdcmT-9vwVFqIeU6ZCTawdDjRGjgQCn81PGlnCW7GVb3fLgpD1A_feFbGxBXVYSbRWA-rHGccyI9kWU5xxWyZwlYpl9_zT8j4mD8CZzffbgsPzag6aspE52fHgPRqz6rYzgZpXS7o6MUOEsjcWiOwp2ManvvnVA0mM_G65jdqMz1rPjdxt19QnQ8V59QtButGQ
