id: dev
debug: true
discovery-server: "localhost:1900"
auth-servers:
  ttn-account: "https://account.thethingsnetwork.org"
  ttn-account-preview: "https://preview.account.thethingsnetwork.org"
  ttn-account-staging: "https://preview.account.thethingsnetwork.org"
tls: true
key-dir: "./.env/handler/"
# handler:
#   amqp-host: localhost:5672
#   amqp-username: guest
#   amqp-password: guest
#   amqp-exchange: topic

auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0dG4tYWNjb3VudC1wcmV2aWV3Iiwic3ViIjoiZGV2IiwidHlwZSI6ImhhbmRsZXIiLCJpYXQiOjE0NzY0Mzk0Mzh9.iIz5KgH41FRLoIIJKVb9dpaZyYjT0W_ujNoSyY3Eg16xkpSuAA2s0NlmEmKBcLEEQXsMNQJd2HnrsDi9RMljRtHQ-pJkqFsb9asHQ6eVmZb7Yx8uGLGG7wmVDlu_R5nNTyvUDvpNoug3pJf13QAfUpNWbN1pgiK2Or0IalDjiCToHCrq9OE08kM0PjXLacuFMhC-OUrsqadHs4WNm8OQYY5yYOpY0G2l4sL0I53QR5kvMjMyoJIrFHD5VNGCFZ-edyaKsGcmZtuR2b-6c9LuI9elsZT9QcdYpANGaepq6cM-inJdtWKEMnhNxDGykxVhBqbBCaYwBgyP4OgBPIrlVg
