debug: true
discovery-server: "localhost:1900"
auth-servers:
  ttn-account: "https://account.thethingsnetwork.org"
  ttn-account-staging: "https://staging.account.thethingsnetwork.org"
tls: true
key-dir: "./.env/networkserver/"
